name: web3_ai_assistant
description: "Flutter Web3 AI Insights"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^15.1.3

  # HTTP Client
  dio: ^5.8.0+1
  dio_cache_interceptor: ^3.5.0
  retrofit: ^4.5.0
  
  # WebSocket
  web_socket_channel: ^3.0.1

  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Logging
  logger: ^2.0.2+1

  # Web3 Integration
  web3dart: ^3.0.1
  
  # HTTP Client for Web3
  http: ^1.4.0

  # Google Fonts
  google_fonts: ^6.2.1

  # Environment Variables
  flutter_dotenv: ^5.2.1

  # Utilities
  uuid: ^4.5.1
  
  # Markdown rendering
  flutter_markdown: ^0.7.5
  
  # Local storage
  shared_preferences: ^2.3.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  riverpod_generator: ^2.6.5
  json_serializable: ^6.9.5
  retrofit_generator: ^9.1.4
  build_runner: ^2.4.13
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  generate: true
  assets:
    - .env
    - assets/

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/ai_insigts_logo.jpg"
    background_color: "#0C0B09"
    theme_color: "#6BE7C8"